### ISSUE TITLE
please update all commands to run Project

### ISSUE THREAD

**Issue by prashantepic** [shahzadali8868/Quote_Project#1]
PHP 8.0.28 or above

Composer version 2.6.5 or above

 Laravel framework: 9.19 or above

**Comment by prashantepic** [comment]
Please update version as mentioned above.

**Comment by shahzadali8868** [comment]
> PHP 8.0.28 or above
> 
> Composer version 2.6.5 or above
> 
> Laravel framework: 9.19 or above

i upgraded the php laravel version 
now you can pull 
and run  #composer update command

**Comment by shahzadali8868** [comment]
> Please update version as mentioned above.

i upgraded the php laravel version
now you can pull
and run #composer update command

**Comment by PremchandraYadav** [comment]
Nice

**Comment by PremchandraYadav** [comment]
Nice
