### ISSUE TITLE
please create custom login/register feature

### ISSUE THREAD

**Issue by PremchandraYadav** [shahzadali8868/Quote_Project#2]
Don't use Laravel command to generate login feature.
Don't use default breeze login feature.
Create custom view, controller, model and authentication

**Comment by shahzadali8868** [comment]
> Don't use Laravel command to generate login feature. Don't use default breeze login feature. Create custom view, controller, model and authentication

sorry i forget remove package from json and lock file now i removed. 
but i already make custom login controller, view  now i also make register now you can check 
make sure first pull afer that run command  #composer install
